### ISSUE TITLE
org capture with org tidy will make capture headline uneditable

### ISSUE THREAD

**Issue by unship** [jxq0/org-tidy#10]
![SCR-20231012-pueo](https://github.com/jxq0/org-tidy/assets/7426917/d441b396-0a4f-4fc0-97d8-dd2929ea7f3c)

emacs 29, doom emacs, 

;; package.el
(package! org-tidy)

;; config.el

(use-package! org-tidy
  :config
  (add-hook 'org-mode-hook #'org-tidy-mode))

**Comment by jxq0** [comment]
@unship Org-tidy will protect the drawers after save. You can use `org-tidy-buffer` to untidy this buffer temporarily.
