### ISSUE TITLE
Feature idea: Configure maximal list of properties to enable

### ISSUE THREAD

**Issue by nickanderson** [jxq0/org-tidy#2]
Nice, package. Thanks for making and sharing it.

I used to be bothered by properties drawers but I guess I just got used to it over time as I started making more use of them. I could see this being much more applicable to me if it were enabled only when a non-standard property were set.

E.g. I have many nodes with just ID and those could be hidden, but when I set other extra properties that I don't often set it might be nicer to show them. For example when I have MAIL_TO set it might make more sense to not hide the properties. Or if I often set PERSON to an link pointing to that persons contact file then only hide properties if there are more than PERSON and ID.

**Comment by jxq0** [comment]
@nickanderson Thanks. It's a gread idea. I will try to implement this feature.

**Comment by jxq0** [comment]
Check https://github.com/jxq0/org-tidy/pull/5 . Add two custom option `org-tidy-property-drawer-property-whitelist` and `org-tidy-property-drawer-property-blacklist`.

For example, you can set `org-tidy-property-drawer-property-blacklist` to `'("MAIL_TO")` to exclude property drawers contains `MAIL_TO` property.
