### ISSUE TITLE
Regression: org-tidy-toggle doesn't work any more

### ISSUE THREAD

**Issue by markokocic** [jxq0/org-tidy#25]
I have org-tidy installed since a long time like this:

``` elisp
(use-package org-tidy
  :ensure t :defer t
  :hook
  (org-mode . org-tidy-mode)
  :bind (("C-c n t" . org-tidy-toggle)))
```

Since some time, when in org buffer, when I invoke `org-tidy-toggle` I get the following error:
```
Wrong type argument: number-or-marker-p, nil
```

Nothing has changed in my configuration, except that I updated both `org-mode` and `org-tidy` to the latest versions.

**Comment by Kintaro** [comment]
Can confirm. Experiencing the same problem here.

**Comment by jxq0** [comment]
@markokocic What's your org-mode version and emacs version?

**Comment by markokocic** [comment]
- GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-07-05 auf Windows
- org-mode version: 9.7.16

**Comment by jxq0** [comment]
@markokocic @Kintaro I have fixed this issue in https://github.com/jxq0/org-tidy/pull/27. You can try the new version.

**Comment by markokocic** [comment]
It works. Thanks.
