### ISSUE TITLE
Feature idea: Hide logbook (and other drawers)

### ISSUE THREAD

**Issue by enbrown** [jxq0/org-tidy#3]
If progress logging is turned on for TODO lists, then logbook drawers will be strewn about the file similar to property drawers. It would be nice to also hide these.  Although the default drawer is called `LOGBOOK`, it can be changed by changing the `LOG_INTO_DRAWER` property. Maybe there could be an option to hide all drawers in addition to property-drawers? Or would that be too drastic?

**Comment by jxq0** [comment]
This feature is done in https://github.com/jxq0/org-tidy/pull/5 .

Now you can use `org-tidy-general-drawer-name-whitelist` and `org-tidy-general-drawer-name-blacklist` to control how to tidy drawers by name.
